# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: et_def.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65t_def.proto\x12\x0e\x43hakraProtoMsg\"\x85\x05\n\x04Node\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x39\n\tnode_type\x18\x03 \x01(\x0e\x32\x18.ChakraProtoMsg.NodeType:\x0cINVALID_NODE\x12\x0e\n\x06parent\x18\x04 \x03(\x04\x12>\n\ntensor_loc\x18\x05 \x01(\x0e\x32\x1a.ChakraProtoMsg.MemoryType:\x0eINVALID_MEMORY\x12\x13\n\x0btensor_size\x18\x06 \x01(\x04\x12\x1a\n\x12simulated_run_time\x18\x07 \x01(\x04\x12\x44\n\x10input_tensor_loc\x18\x08 \x01(\x0e\x32\x1a.ChakraProtoMsg.MemoryType:\x0eINVALID_MEMORY\x12\x19\n\x11input_tensor_size\x18\t \x01(\x04\x12\x45\n\x11output_tensor_loc\x18\n \x01(\x0e\x32\x1a.ChakraProtoMsg.MemoryType:\x0eINVALID_MEMORY\x12\x1a\n\x12output_tensor_size\x18\x0b \x01(\x04\x12\x0f\n\x07num_ops\x18\x0c \x01(\x04\x12\x43\n\tcomm_type\x18\r \x01(\x0e\x32\".ChakraProtoMsg.CollectiveCommType:\x0cINVALID_COMM\x12\x14\n\x0cinvolved_dim\x18\x0e \x03(\x08\x12\x17\n\x0f\x63ommunicator_id\x18\x0f \x01(\r\x12\x10\n\x08\x63omm_src\x18\x10 \x01(\r\x12\x10\n\x08\x63omm_dst\x18\x11 \x01(\r\x12\x11\n\tcomm_size\x18\x12 \x01(\x04\x12\x10\n\x08\x63omm_tag\x18\x13 \x01(\r\x12\x15\n\rcomm_priority\x18\x14 \x01(\r*\x8e\x01\n\x08NodeType\x12\x10\n\x0cINVALID_NODE\x10\x00\x12\x11\n\rMEM_LOAD_NODE\x10\x01\x12\x12\n\x0eMEM_STORE_NODE\x10\x02\x12\r\n\tCOMP_NODE\x10\x03\x12\x12\n\x0e\x43OMM_SEND_NODE\x10\x04\x12\x12\n\x0e\x43OMM_RECV_NODE\x10\x05\x12\x12\n\x0e\x43OMM_COLL_NODE\x10\x06*E\n\nMemoryType\x12\x12\n\x0eINVALID_MEMORY\x10\x00\x12\x10\n\x0cLOCAL_MEMORY\x10\x01\x12\x11\n\rREMOTE_MEMORY\x10\x02*j\n\x12\x43ollectiveCommType\x12\x10\n\x0cINVALID_COMM\x10\x00\x12\x0e\n\nALL_REDUCE\x10\x01\x12\x0e\n\nALL_TO_ALL\x10\x02\x12\x0e\n\nALL_GATHER\x10\x03\x12\x12\n\x0eREDUCE_SCATTER\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'et_def_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODETYPE']._serialized_start=681
  _globals['_NODETYPE']._serialized_end=823
  _globals['_MEMORYTYPE']._serialized_start=825
  _globals['_MEMORYTYPE']._serialized_end=894
  _globals['_COLLECTIVECOMMTYPE']._serialized_start=896
  _globals['_COLLECTIVECOMMTYPE']._serialized_end=1002
  _globals['_NODE']._serialized_start=33
  _globals['_NODE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
